type ApiValue = string | number | boolean | null;
export type Query = Record<string, ApiValue | undefined>;
export type ApiObject = Record<string, unknown>;
export type TeamIdentifier = string | number;
export type TeamResponse = {
    abbreviation: string | null;
    id: number;
    city: string | null;
    name: string | null;
    fullName: string | null;
};
export type ArenaResponse = {
    name: string | null;
    city: string | null;
    state: string | null;
    attendance: number;
};
export type PeriodResponse = {
    period: number;
    periodType: string | null;
    score: number;
};
export type PlayerStatisticsResponse = {
    minutes: string;
    points: number;
    assists: number;
    reboundsTotal: number;
    reboundsOffensive: number;
    reboundsDefensive: number;
    steals: number;
    blocks: number;
    foulsPersonal: number;
    turnovers: number;
    plusMinusPoints: number;
    fieldGoalsMade: number;
    fieldGoalsAttempted: number;
    fieldGoalsPercentage: number;
    twoPointersMade: number;
    twoPointersAttempted: number;
    twoPointersPercentage: number;
    threePointersMade: number;
    threePointersAttempted: number;
    threePointersPercentage: number;
    freeThrowsMade: number;
    freeThrowsAttempted: number;
    freeThrowsPercentage: number;
};
export type BoxScorePlayerResponse = {
    personId: number;
    firstName: string;
    familyName: string;
    jerseyNumber: string;
    position: string | null;
    status: string;
    played: boolean;
    starter: boolean;
    statistics: PlayerStatisticsResponse;
};
export type TeamScoreResponse = {
    team: TeamResponse;
    score: number | null;
    wins: number;
    losses: number;
    periods: PeriodResponse[] | null;
    players: BoxScorePlayerResponse[];
};
export type ScheduleGameResponse = {
    gameId: string | null;
    startTime: string;
    seasonType: number;
    gameLabel: string | null;
    visitingTeam: TeamResponse;
    homeTeam: TeamResponse;
    arena: ArenaResponse;
    media: ApiObject[] | null;
};
export type BoxScoreResponse = {
    gameId: string | null;
    isAvailable: boolean;
    gameState: string | null;
    startTimeUtc: string;
    startTimeEastern: string;
    gameCode: string | null;
    gameClock: string | null;
    gameStatusText: string | null;
    period: number;
    arena: ArenaResponse;
    visitor: TeamScoreResponse;
    home: TeamScoreResponse;
    officials: ApiObject[] | null;
};
export type PlayerResponse = {
    id: number;
    teamId: number;
    season: string | null;
    leagueId: string | null;
    name: string | null;
    nickname: string | null;
    playerSlug: string | null;
    jerseyNumber: string | null;
    position: string | null;
    height: string | null;
    weight: string | null;
    birthDate: string | null;
    age: string | null;
    experience: string | null;
    school: string | null;
    howAcquired: string | null;
    supplementalStatus: number;
};
export type SeasonResponse = {
    value: string | null;
    label: string | null;
    startYear: number;
    endYear: number;
    isCurrent: boolean;
};
export type RecordResponse = {
    team: string | null;
    record: string | null;
    wins: string | null;
    losses: string | null;
};
export type StandingResponse = {
    team: TeamResponse;
    conference: number;
    wins: string | null;
    losses: string | null;
    winPercentage: string | null;
    gamesBehind: number;
    streak: string | null;
};
export type StatsResultSetResponse = {
    name: string | null;
    headers: string[] | null;
    rows: Record<string, string>[] | null;
};
export type StatsResponse = {
    resource: string | null;
    parameters: Record<string, string | null> | null;
    resultSets: StatsResultSetResponse[] | null;
};
export type GameActionResponse = ApiObject;
export type PlayerSearchResponse = ApiObject;
export type LeagueLeaderResponse = ApiObject;
export type TeamDashboardResponse = ApiObject;
export type LineupCombinationsResponse = ApiObject;
export type PlayerCareerStatsResponse = ApiObject;
export type PlayerGameLogResponse = ApiObject;
export type PlayerTrackingResponse = ApiObject;
export declare class CavsBotApiError extends Error {
    readonly status: number;
    readonly path: string;
    constructor(message: string, status: number, path: string);
}
export declare class CavsBotApiClient {
    private readonly baseUrl;
    constructor(baseUrl?: string);
    request<T>(path: string, query?: Query, init?: RequestInit): Promise<T>;
    health(): Promise<void>;
    teams(): Promise<TeamResponse[]>;
    team(team: TeamIdentifier): Promise<TeamResponse>;
    seasons(): Promise<SeasonResponse[]>;
    teamPlayers(team: TeamIdentifier, season?: string): Promise<PlayerResponse[]>;
    teamRoster(team: TeamIdentifier, season?: string): Promise<PlayerResponse[]>;
    teamCoaches(team: TeamIdentifier, season?: string): Promise<ApiObject[]>;
    teamSchedule(team: TeamIdentifier, query?: Query): Promise<ScheduleGameResponse[]>;
    game(gameId: string): Promise<ScheduleGameResponse>;
    scoreboard(date?: string): Promise<ScheduleGameResponse[]>;
    scoreboardToday(): Promise<ScheduleGameResponse[]>;
    nextGame(team: TeamIdentifier): Promise<ScheduleGameResponse>;
    previousGame(team: TeamIdentifier): Promise<ScheduleGameResponse>;
    recentForm(team: TeamIdentifier, count?: number): Promise<ScheduleGameResponse[]>;
    matchups(team: TeamIdentifier, opponent: TeamIdentifier, count?: number): Promise<ScheduleGameResponse[]>;
    playByPlay(gameId: string): Promise<ApiObject[]>;
    players(query?: Query): Promise<ApiObject[]>;
    player(playerId: number): Promise<ApiObject>;
    playerTeams(playerId: number): Promise<ApiObject>;
    playerRosterHistory(playerId: number): Promise<ApiObject>;
    playerGameLog(playerId: number, query?: Query): Promise<ApiObject[]>;
    playerStats(playerId: number, query?: Query): Promise<StatsResponse>;
    playerShotChart(playerId: number, query?: Query): Promise<StatsResponse>;
    playerStatsDashboard(query?: Query): Promise<StatsResponse>;
    playerAdvancedStats(query?: Query): Promise<StatsResponse>;
    playerSplits(playerId: number, query?: Query): Promise<StatsResponse>;
    playerAdvancedStatsById(playerId: number, query?: Query): Promise<StatsResponse>;
    playerTracking(playerId: number, query?: Query): Promise<ApiObject>;
    playerAwards(playerId: number): Promise<ApiObject[]>;
    teamStats(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    teamAdvancedStats(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    teamGameLog(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    teamSplits(team: TeamIdentifier, query?: Query): Promise<ApiObject>;
    teamLineups(team: TeamIdentifier, query?: Query): Promise<ApiObject>;
    teamLineupCombinations(team: TeamIdentifier, query?: Query): Promise<ApiObject>;
    teamOnOff(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    teamClutch(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    teamFourFactors(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    teamOpponentStats(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    teamQuarterStats(team: TeamIdentifier, query?: Query): Promise<StatsResponse>;
    leaders(query?: Query): Promise<ApiObject[]>;
    standings(query?: Query): Promise<StandingResponse[]>;
    record(team: TeamIdentifier, seasonType?: number): Promise<RecordResponse>;
    boxScore(gameId: string): Promise<BoxScoreResponse>;
}
export declare const cavsBotApi: CavsBotApiClient;
export {};
